name: Publish Docker Images

on:
  push:
    branches: [main]

jobs:

  publish:
    strategy:
      matrix:
        dockerimage: ["dockersshd", "simplesshd"]
    name: Publish '${{ matrix.dockerimage }}' image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/login-action@v1  
        with:
          registry: docker.pkg.github.com
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build '${{ matrix.dockerimage }}' Image
        run: docker build -f docker/${{ matrix.dockerimage }}/Dockerfile -t docker.pkg.github.com/${{ github.repository }}/${{ matrix.dockerimage }}:latest .
      - name: Publish '${{ matrix.dockerimage }}' Image
        run: docker push docker.pkg.github.com/${{ github.repository }}/${{ matrix.dockerimage }}:latest