name: Publish Docker Images

on:
  push:
    branches: [main]

jobs:
  publish:
    name: Dockerfile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/login-action@v1  
        with:
          registry: docker.pkg.github.com
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build 'dockersshd' Image
        run: docker build -f Dockerfile -t docker.pkg.github.com/${{ github.repository }}/dockersshd:latest .
      - name: Publish 'dockersshd' Image
        run: docker push docker.pkg.github.com/${{ github.repository }}/dockersshd:latest
  publishsimple:
    name: Dockerfile.simple
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build 'simplesshd' Image
        run: docker build -f Dockerfile.simple -t docker.pkg.github.com/${{ github.repository }}/simplesshd:latest .
      - name: Publish 'simplesshd' Image
        run: docker push docker.pkg.github.com/${{ github.repository }}/simplesshd:latest