name: Publish Docker Images

on:
  push:
    branches: [main]

env:
  REGISTRY: ghcr.io
  IMAGE_BASENAME: tkw1536
  PLATFORMS: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6

jobs:
  publish:
    strategy:
      matrix:
        dockerimage: ["dockersshd", "simplesshd", "exposshed"]
    name: Publish '${{ matrix.dockerimage }}' image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ${{ env.REGISTRY }}
      - uses: docker/build-push-action@v2
        with:
          file: ./cmd/${{ matrix.dockerimage }}/Dockerfile
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_BASENAME }}/${{ matrix.dockerimage }}:latest
          platforms: ${{ env.PLATFORMS }}
          pull: true
          push: true
