name: Publish Docker Images

on:
  push:
    branches: [main]

jobs:
  publish:
    strategy:
      matrix:
        dockerimage: ["dockersshd", "simplesshd", "exposshed"]
    name: Publish '${{ matrix.dockerimage }}' image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
          registry: ghcr.io
      - uses: docker/build-push-action@v2
        with:
          file: ./docker/${{ matrix.dockerimage }}/Dockerfile
          tags: ghcr.io/tkw1536/${{ matrix.dockerimage }}:latest
          platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6
          pull: true
          push: true
