name: CI

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-go@v2
        - name: Check that 'gofmt' has been run
          run: test -z $(gofmt -l .)
  test:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-go@v2
        - name: Run 'go test'
          run: go test ./...
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
      - name: Install gogenlicense
        run: go get github.com/tkw1536/gogenlicense/cmd/gogenlicense
      - uses: actions/checkout@v2
      - name: Update licenses
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          go generate ./...
        - name: Build executables
          run: |
            go build ./cmd/dockersshd
            go build ./cmd/simplesshd
        - name: Upload executables
          uses: actions/upload-artifact@v2
          with:
            name: Binaries
            path: dist/*
  dockerfile:
    name: Dockerfile
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - name: Build 'Dockerfile'
          run: docker build -f Dockerfile -t proxyssh:latest .
  dockerfile-simple:
    name: Dockerfile.simple
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - name: Build 'Dockerfile.simple'
          run: docker build -f Dockerfile.simple -t proxyssh:latest .