name: CI

on: [push, pull_request]

env:
  GO_VERSION: '^1.18'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-go@v2
          with:
            go-version: ${{ env.GO_VERSION }}
        - name: Check that 'gofmt' has been run
          run: test -z $(gofmt -l .)
  test:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-go@v2
          with:
            go-version: ${{ env.GO_VERSION }}
        - name: Run 'go test'
          run: go test -tags=leak,dockertest ./...
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Install gogenlicense
        run: go install github.com/tkw1536/gogenlicense/cmd/gogenlicense@latest
      - uses: actions/checkout@v2
      - name: Update licenses
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          go generate ./...
      - name: Build executables (with leak)
        run: |
          go build -tags=leak ./cmd/dockersshd
          go build -tags=leak ./cmd/simplesshd
          go build -tags=leak ./cmd/exposshed
      - name: Build executables
        run: |
          go build ./cmd/dockersshd
          go build ./cmd/simplesshd
          go build ./cmd/exposshed
  docker:
    strategy:
      matrix:
        dockerimage: ["dockersshd", "simplesshd", "exposshed"]
    name: "Build '${{ matrix.dockerimage }}' Docker Image"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build '${{ matrix.dockerimage }}' docker image
        run: docker build -f cmd/${{ matrix.dockerimage }}/Dockerfile -t ${{ matrix.dockerimage }}:latest .